Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,7 +27,7 @@ jobs:
 
       - name: Deploy Strapi Application
         run: |
-          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.ASHOK_EC2_HOST }} "
+          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@*** "
             sudo mkdir -p /srv/strapi && sudo chown ubuntu:ubuntu /srv/strapi
             cd /srv/strapi
             if [ -d '.git' ]; then
@@ -35,9 +35,15 @@ jobs:
             else
               git clone https://github.com/veera1016/strapi.git /srv/strapi
             fi
-            npm install
-            npm run build
-            pm2 restart strapi || pm2 start npm --name 'strapi' -- run start
+            ls -la /srv/strapi
+            if [ -f /srv/strapi/package.json ]; then
+              npm install
+              npm run build
+              pm2 restart strapi || pm2 start npm --name 'strapi' -- run start
+            else
+              echo 'Error: package.json not found in /srv/strapi'
+              exit 1
+            fi
           "
 
       - name: Clean up
